baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Praneeth G'
theme = 'nightfall'

[params]
    user = "praneeth"
    hostname = "gohugo.io"
    sitedescription = 'Find all my about me and my career here'
    published = false
    readingTime = false
    footerHtml = 'Majoring in Masters in Computer Science at <a href="https://vt.edu/" class="footerLink">Virginia Tech</a>'

    [params.author]
        name = "Hi 👋, I'm Praneeth"
        email = "inboxpraneeth@gmail.com"

    [[params.social]]
        key = 1
        name = "github"
        url = "https://github.com/PraneethGunas"
        target = "_blank"
        aria = "Praneeth GitHub" # Define the aria label for accessibility like page reader - this is better for your SEO

    [[params.social]]
        key = 2
        name = "twitter"
        target = "_blank"
        url = "https://x.com/PraneethGunas"

    [[params.social]]
        key = 3
        name = "linkedin"
        url = "https://www.linkedin.com/in/praneeth-g/"
        target = "_blank"
        rel = "me"  # You can also add rel to social link

    [[params.social]]
        key = 4
        name = "email"
        target = "_blank"
        url = "mailto:inboxpraneeth@gmail.com"

    [[params.social]]
        key = 5
        name = "resume"
        url = "https://docs.google.com/document/d/1zTrQzRxBieHahgyPNkKCuI8i7kqn5CJeLcf2uesJ_cE/preview?format=pdf"
        target = "_blank"
    

    [menu]
        [[menu.header]]
            name = "about"
            weight = 1
            url = "/about/"
        
        [[menu.header]]
            name = "curriculum"
            weight = 1
            url = "/curriculum/"

        [[menu.header]]
            name = "projects"
            weight = 1
            url = "/projects/"
